### ISSUE TITLE
doesn't seem to work when wifi is disabled?

### ISSUE THREAD

**Issue by max-mapper** [hoodiehq-archive/local-tld#13]
(disclaimer: i'm not sure if this is the correct repo to report this bug)

in a fresh hoodie app if I have wifi turned off or if I'm not associated with an access point doing `hoodie start` opens a browser window to `appname.dev` but chrome shows `Unable to connect to the Internet` until I turn wifi on and connect to a network

**Comment by gr2m** [comment]
hmm, does it work with http://? http://appname.dev

**Comment by max-mapper** [comment]
nope, cant get chrome to do it, tried an incognito window + disabled cache in dev tools and always get the error page. works fine with curl

**Comment by janl** [comment]
Iirc this doesn't work with wifi off. I remember pow having a open issue for quite a while.

There might be workarounds.

**Comment by max-mapper** [comment]
is there a workflow for using hoodie without the automagic tld?

**Comment by janl** [comment]
It's in the works. Let me get back from Dublin to review some code :)

**Comment by max-mapper** [comment]
any update on this? I just updated to the newest version of all the hoodie stuff but it still won't work if i'm not connected to some wifi network

**Comment by gr2m** [comment]
I think that's fixed, at least it works for me™ ;-) I'm not involved in the code though

try to update local-tld and the hoodie dependencies (hoodie-app and workers).

Also the hoodie CLI tool is now an npm package as well. Remove the current one, then run `npm install -g hoodie-cli`

**Comment by max-mapper** [comment]
ok I did `npm install -g hoodie-cli` and then cloned master hoodie-app, then turned off wifi and then ran `hoodie`. still get the same behavior (hoodie doesnt serve anything)

**Comment by gr2m** [comment]
you're on a Mac, right? What errors do you get?

Note that the hoodie api is not api.myapp.dev anymore, it now is myapp.dev/_api. But hoodie.js should use /_api  as a default. Also make sure to update hoodie.js if the problem occurs in an older app.

Maybe just to test, could you try to create a new app with `hoode new whereisthesun`

**Comment by max-mapper** [comment]
`curl http://whereisthesun.dev` returns html but chrome/safari/firefox all refuse to resolve the address unless I'm online

**Comment by gr2m** [comment]
I don't know if that's what biting you, but the first time I open a newappname.dev in the browser, I've to explicitly add the `http://`. When I just put in `whereisthesun.dev` it uses it as a search term for Google.

Might that be the problem?

**Comment by max-mapper** [comment]
nope, that's not it. also related issue:
https://github.com/hoodiehq/hoodie-app/issues/39

**Comment by gr2m** [comment]
damn, sorry I can't help better. @janl @caolan can you help here?

I think the local-tld thing is opitonal already, but I'm not 10)% sure. But I guess that would resolve your issue, if you could just use localhost:1234 instead of the dev domains, right?

**Comment by janl** [comment]
There is no solution to this. The only workaround is treating the Mac like a Linux and using localhost&ports. @caolan should be able to get you set up.
