### ISSUE TITLE
Compatibility with Yosemite

### ISSUE THREAD

**Issue by allaire** [hoodiehq-archive/local-tld#26]
Might be interesting to follow what come up here: https://github.com/basecamp/pow/issues/452

ipfw is removed from yosemite, so we might have to backport some of the suff in pow again!

**Comment by janl** [comment]
Wo, thanks for the heads up!

**Comment by brndnblck** [comment]
Maybe just use pow's port proxy feature and call it a day for `local-tld`?

http://pow.cx/manual.html#section_2.1.4

``` bash
# http://myapp.dev
$ echo 8000 > ~/.pow/myapp
```

**Comment by janl** [comment]
@brandonblack I love pow, but the reason for me to have local-tld is a pure Node solution, as that makes the installation story for our users a lot simpler. Not saying pow or Ruby are particularly difficult, it’s just another thing that has different conventions and all that, hence my “clone” :)

**Comment by tv** [comment]
Here are quick steps to get local-tld working in Yosemite. I don't have time right now to make fix but needed this working asap, so had to tinker around. Hope this saves some time from someone else.

### /etc/pf.anchors/local.dev

```
rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port = 80 -> 127.0.0.1 port 5999
```

### /etc/pf.conf

After rdr-anchor "com.apple" add

```
rdr-anchor "local.dev"
```

Bottom of the file add

```
load anchor "local.dev" from "/etc/pf.anchors/local.dev"
```

### Restart PF

```
sudo pfctl -f /etc/pf.conf
sudo pfctl -e
```

**Comment by servel333** [comment]
This worked to get local-tld working for me, however is it normal to get these warnings?

```
$ sudo pfctl -f /etc/pf.conf
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
$ sudo pfctl -e
No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
```

**Comment by tv** [comment]
As far as I know, these are completely normal. It just informs that some pf functions are unavailable under OS X kernel. However, we don't even need those functions, so you can safely ignore the warnings.

**Comment by servel333** [comment]
Perfect. Thanks.

**Comment by hnrch02** [comment]
Thanks for the workaround @tv, but every time I restart my system I need to enter both `sudo pfctl -f /etc/pf.conf` and `sudo pfctl -e` again. Is there some way to avoid that?

**Comment by tv** [comment]
You will need to create LaunchDaemon to handle pf startup at launch time. I rarely restart my system, so didn't bother to create this. Check local-tld-firewall.plist for reference.

**Comment by hnrch02** [comment]
@tv Thanks!

**Comment by JamesKyburz** [comment]
Thx for this!

**Comment by xizhao** [comment]
This doesn't seem to fix it on Yosemite for me, I still had to do the manual workaround.
