### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by sjelfull** [hoodiehq-archive/local-tld#28]
Okay, running on Lion, and got two problems.

First, it doesn't seem like I could get it to run properly. I'm using MAMP, running on port 80, where I have many sites.

I installed via npm install -g, as expected.

I tried adding one of them: 
{
  "80": {
    "name": "app"
  }
}

I'm unable to connect.

$ telnet app.dev 80
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host

What is worse, when I try to uninstall, I continue to get connection refused.

What's going on behind the scenes?

On a side note, is it possible to have multiple sites running on the same port (follow my MAMP setup)?

To clarify: I've tried uninstalling several times, but i'm not back to the way things were before install.

**Comment by sjelfull** [comment]
I'm seeing this in Console log:

20/08/14 23:31:15,183 com.apple.launchd.peruser.501[298]: (ie.hood.local-tld-service[36442]) Job failed to exec(3). Setting up event to tell us when to try again: 2: No such file or directory
20/08/14 23:31:15,183 com.apple.launchd.peruser.501[298]: (ie.hood.local-tld-service[36442]) Job failed to exec(3) for weird reason: 2

**Comment by sjelfull** [comment]
Thanks to some lovely help on IRC, it turns out the missing piece was to flush all rules with 
`ipfw flush`

ipfw is deprecated, so pfctl -F all seems to do the same thing.

**Comment by gr2m** [comment]
@sjelfull can we close this issue?

**Comment by sjelfull** [comment]
@gr2m Yep, do it.
